import { defineObject, FieldType } from 'twenty-sdk/define';

import { fieldId, MESSAGE_BODY } from 'src/constants/field-identifiers';
import { OBJ_MESSAGE } from 'src/constants/universal-identifiers';

const f = (name: string) => fieldId(OBJ_MESSAGE, name);

/**
 * The high-volume table (NFR-S1: 50 000 messages/day design headroom).
 *
 * Neither UI-creatable nor UI-editable: messages are written only by the app.
 * A hand-edited record would desynchronise from Meta, and `wamid` uniqueness is
 * the idempotency guarantee the whole ingestion path rests on (AR-8).
 */
export default defineObject({
  universalIdentifier: OBJ_MESSAGE,
  nameSingular: 'whatsappMessage',
  namePlural: 'whatsappMessages',
  labelSingular: 'WhatsApp message',
  labelPlural: 'WhatsApp messages',
  description: 'A single WhatsApp message, inbound or outbound',
  icon: 'IconMessage',
  isUICreatable: false,
  isUIEditable: false,
  labelIdentifierFieldMetadataUniversalIdentifier: MESSAGE_BODY,
  fields: [
    {
      universalIdentifier: MESSAGE_BODY,
      name: 'body',
      label: 'Body',
      description: 'Text or caption; the placeholder string for unsupported types (FR-IN-1)',
      icon: 'IconMessage',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('wamid'),
      name: 'wamid',
      label: 'WAMID',
      description:
        "Meta's message id — the idempotency key (AR-8). Null between queued and accepted for outbound",
      icon: 'IconFingerprint',
      type: FieldType.TEXT,
      isNullable: true,
      isUnique: true,
    },
    {
      universalIdentifier: f('direction'),
      name: 'direction',
      label: 'Direction',
      icon: 'IconArrowsUpDown',
      type: FieldType.SELECT,
      defaultValue: "'INBOUND'",
      options: [
        { value: 'INBOUND', label: 'Inbound', position: 0, color: 'green' },
        { value: 'OUTBOUND', label: 'Outbound', position: 1, color: 'blue' },
      ],
    },
    {
      universalIdentifier: f('messageType'),
      name: 'messageType',
      label: 'Type',
      description:
        'Named `messageType` because `type` is reserved by the server, which would otherwise append a "Custom" suffix',
      icon: 'IconCategory',
      type: FieldType.SELECT,
      defaultValue: "'TEXT'",
      options: [
        { value: 'TEXT', label: 'Text', position: 0, color: 'blue' },
        { value: 'IMAGE', label: 'Image', position: 1, color: 'purple' },
        { value: 'AUDIO', label: 'Audio', position: 2, color: 'pink' },
        { value: 'VIDEO', label: 'Video', position: 3, color: 'violet' },
        { value: 'DOCUMENT', label: 'Document', position: 4, color: 'orange' },
        { value: 'STICKER', label: 'Sticker', position: 5, color: 'yellow' },
        { value: 'LOCATION', label: 'Location', position: 6, color: 'green' },
        { value: 'CONTACTS', label: 'Contact card', position: 7, color: 'jade' },
        { value: 'REACTION', label: 'Reaction', position: 8, color: 'gold' },
        { value: 'INTERACTIVE', label: 'Interactive', position: 9, color: 'sky' },
        { value: 'BUTTON_REPLY', label: 'Button reply', position: 10, color: 'sky' },
        { value: 'LIST_REPLY', label: 'List reply', position: 11, color: 'sky' },
        { value: 'TEMPLATE', label: 'Template', position: 12, color: 'iris' },
        { value: 'SYSTEM', label: 'System', position: 13, color: 'gray' },
        { value: 'UNSUPPORTED', label: 'Unsupported', position: 14, color: 'gray' },
      ],
    },
    {
      universalIdentifier: f('payload'),
      name: 'payload',
      label: 'Payload',
      description: 'Full typed payload: coordinates, contact cards, interactive structures, reactions',
      icon: 'IconBraces',
      type: FieldType.RAW_JSON,
      isNullable: true,
    },
    {
      universalIdentifier: f('status'),
      name: 'status',
      label: 'Status',
      description: 'Monotonic (AR-9). Inbound messages are created directly at delivered',
      icon: 'IconChecks',
      type: FieldType.SELECT,
      defaultValue: "'QUEUED'",
      options: [
        { value: 'QUEUED', label: 'Queued', position: 0, color: 'gray' },
        { value: 'ACCEPTED', label: 'Accepted', position: 1, color: 'blue' },
        { value: 'SENT', label: 'Sent', position: 2, color: 'sky' },
        { value: 'DELIVERED', label: 'Delivered', position: 3, color: 'turquoise' },
        { value: 'READ', label: 'Read', position: 4, color: 'green' },
        { value: 'PLAYED', label: 'Played', position: 5, color: 'green' },
        { value: 'FAILED', label: 'Failed', position: 6, color: 'red' },
      ],
    },
    {
      universalIdentifier: f('statusTimestamps'),
      name: 'statusTimestamps',
      label: 'Status timestamps',
      description:
        'Every observed transition, recorded even when the status field does not move. Meta timestamps are 1-second resolution and collide, so they are audit only (AR-9)',
      icon: 'IconTimeline',
      type: FieldType.RAW_JSON,
      isNullable: true,
    },
    {
      universalIdentifier: f('errorCode'),
      name: 'errorCode',
      label: 'Error code',
      description: 'Meta numeric code as a string, or an internal code such as POLICY_WINDOW_CLOSED',
      icon: 'IconAlertCircle',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('errorDetail'),
      name: 'errorDetail',
      label: 'Error detail',
      description: 'Raw Meta title/details, untranslated — the UI owns the copy',
      icon: 'IconAlertCircle',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('retryCount'),
      name: 'retryCount',
      label: 'Retries',
      icon: 'IconRefresh',
      type: FieldType.NUMBER,
      defaultValue: 0,
    },
    {
      universalIdentifier: f('templateParameters'),
      name: 'templateParameters',
      label: 'Template parameters',
      description: 'Resolved variables (FR-TPL-5)',
      icon: 'IconVariable',
      type: FieldType.RAW_JSON,
      isNullable: true,
    },
    {
      universalIdentifier: f('templateName'),
      name: 'templateName',
      label: 'Template name',
      description: 'Denormalised so the audit trail survives template deletion',
      icon: 'IconTemplate',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('templateLanguage'),
      name: 'templateLanguage',
      label: 'Template language',
      icon: 'IconLanguage',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('templateCategory'),
      name: 'templateCategory',
      label: 'Template category',
      description: 'The billing driver (FR-TPL-5)',
      icon: 'IconCash',
      type: FieldType.SELECT,
      isNullable: true,
      options: [
        { value: 'MARKETING', label: 'Marketing', position: 0, color: 'purple' },
        { value: 'UTILITY', label: 'Utility', position: 1, color: 'blue' },
        { value: 'AUTHENTICATION', label: 'Authentication', position: 2, color: 'orange' },
      ],
    },
    {
      universalIdentifier: f('billableCostUsd'),
      name: 'billableCostUsd',
      label: 'Cost (USD)',
      description: 'Written on delivered for billable categories — Meta bills on delivery',
      icon: 'IconCurrencyDollar',
      type: FieldType.NUMBER,
      isNullable: true,
    },
    {
      universalIdentifier: f('mediaFile'),
      name: 'mediaFile',
      label: 'Media',
      icon: 'IconPaperclip',
      type: FieldType.FILES,
      isNullable: true,
      // FILES requires maxNumberOfValues just as ARRAY does. A WhatsApp message
      // carries at most one media attachment.
      universalSettings: { maxNumberOfValues: 1 },
    },
    {
      universalIdentifier: f('mediaMeta'),
      name: 'mediaMeta',
      label: 'Media metadata',
      description:
        'mediaId, mimeType, fileSize, sha256, filename, inlineUrl, deferred, downloadFailed, downloadAttempts',
      icon: 'IconInfoCircle',
      type: FieldType.RAW_JSON,
      isNullable: true,
    },
    {
      universalIdentifier: f('contextWamid'),
      name: 'contextWamid',
      label: 'In reply to',
      description: 'Quoted-reply reference (FR-OUT-3)',
      icon: 'IconArrowBackUp',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('reactionTargetWamid'),
      name: 'reactionTargetWamid',
      label: 'Reaction target',
      icon: 'IconMoodSmile',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('waTimestamp'),
      name: 'waTimestamp',
      label: 'Sent at',
      description: "Meta's message timestamp — the chat ordering key",
      icon: 'IconClock',
      type: FieldType.DATE_TIME,
      defaultValue: 'now',
    },
    {
      universalIdentifier: f('lane'),
      name: 'lane',
      label: 'Lane',
      description: 'Which pacing lane scheduled this send (specs/00 D-5)',
      icon: 'IconRoad',
      type: FieldType.SELECT,
      defaultValue: "'INTERACTIVE'",
      options: [
        { value: 'INTERACTIVE', label: 'Interactive', position: 0, color: 'green' },
        { value: 'CAMPAIGN', label: 'Campaign', position: 1, color: 'purple' },
      ],
    },
    {
      universalIdentifier: f('sourceKind'),
      name: 'sourceKind',
      label: 'Source',
      description: 'What caused the send (audit, FR-OUT-6)',
      icon: 'IconSource',
      type: FieldType.SELECT,
      defaultValue: "'AGENT'",
      options: [
        { value: 'AGENT', label: 'Agent', position: 0, color: 'blue' },
        { value: 'WORKFLOW', label: 'Workflow', position: 1, color: 'purple' },
        { value: 'CAMPAIGN', label: 'Campaign', position: 2, color: 'violet' },
        { value: 'SYSTEM', label: 'System', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: f('clientToken'),
      name: 'clientToken',
      label: 'Client token',
      description:
        'Browser-generated idempotency key: a repeat send with the same token returns the existing message instead of sending twice',
      icon: 'IconKey',
      type: FieldType.TEXT,
      isNullable: true,
      // The unique index is the idempotency guarantee: two concurrent retries
      // both pass the read-then-check, and the second *create* is what fails.
      isUnique: true,
    },
  ],
});
