import { defineObject, FieldType } from 'twenty-sdk/define';

import { ACCOUNT_NAME, fieldId } from 'src/constants/field-identifiers';
import { OBJ_ACCOUNT } from 'src/constants/universal-identifiers';

const f = (name: string) => fieldId(OBJ_ACCOUNT, name);

/**
 * One record per registered Meta business phone number (FR-ACC-1, FR-ACC-6).
 *
 * `isUICreatable: false` — accounts are created only by `wa-account-admin-route`,
 * because connecting a number also writes the SERVER-scoped kv claim that routes
 * webhooks to this workspace (specs/00 D-3). A hand-created record would have no
 * claim and would silently receive nothing.
 */
export default defineObject({
  universalIdentifier: OBJ_ACCOUNT,
  nameSingular: 'whatsappAccount',
  namePlural: 'whatsappAccounts',
  labelSingular: 'WhatsApp account',
  labelPlural: 'WhatsApp accounts',
  description: 'A registered WhatsApp Business phone number',
  icon: 'IconBrandWhatsapp',
  isUICreatable: false,
  labelIdentifierFieldMetadataUniversalIdentifier: ACCOUNT_NAME,
  fields: [
    {
      universalIdentifier: ACCOUNT_NAME,
      name: 'name',
      label: 'Name',
      description: 'Label for this number, e.g. "Sales — Luanda"',
      icon: 'IconTag',
      type: FieldType.TEXT,
      defaultValue: "''",
    },
    {
      universalIdentifier: f('phoneNumberId'),
      name: 'phoneNumberId',
      label: 'Phone number ID',
      description: "Meta's phone_number_id — used in every send call, never the raw number",
      icon: 'IconHash',
      type: FieldType.TEXT,
      isNullable: true,
      defaultValue: null,
      isUnique: true,
    },
    {
      universalIdentifier: f('wabaId'),
      name: 'wabaId',
      label: 'WABA ID',
      description: 'WhatsApp Business Account ID that owns this number',
      icon: 'IconBuildingStore',
      type: FieldType.TEXT,
      defaultValue: "''",
    },
    {
      universalIdentifier: f('displayPhoneNumber'),
      name: 'displayPhoneNumber',
      label: 'Display number',
      icon: 'IconPhone',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('displayName'),
      name: 'displayName',
      label: 'Display name',
      description: 'Approved WhatsApp display name',
      icon: 'IconSignature',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('status'),
      name: 'status',
      label: 'Status',
      icon: 'IconPlugConnected',
      type: FieldType.SELECT,
      defaultValue: "'PENDING'",
      options: [
        { value: 'PENDING', label: 'Pending', position: 0, color: 'gray' },
        { value: 'CONNECTED', label: 'Connected', position: 1, color: 'green' },
        { value: 'ERROR', label: 'Error', position: 2, color: 'red' },
        { value: 'DISABLED', label: 'Disabled', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: f('statusDetail'),
      name: 'statusDetail',
      label: 'Status detail',
      description: 'Why the connection is in error (FR-ACC-4)',
      icon: 'IconAlertTriangle',
      type: FieldType.TEXT,
      isNullable: true,
    },
    {
      universalIdentifier: f('qualityRating'),
      name: 'qualityRating',
      label: 'Quality rating',
      description: 'Meta quality rating for this number (FR-ACC-3)',
      icon: 'IconHeartRateMonitor',
      type: FieldType.SELECT,
      defaultValue: "'UNKNOWN'",
      options: [
        { value: 'GREEN', label: 'Green', position: 0, color: 'green' },
        { value: 'YELLOW', label: 'Yellow', position: 1, color: 'yellow' },
        { value: 'RED', label: 'Red', position: 2, color: 'red' },
        { value: 'UNKNOWN', label: 'Unknown', position: 3, color: 'gray' },
      ],
    },
    {
      universalIdentifier: f('messagingLimitTier'),
      name: 'messagingLimitTier',
      label: 'Messaging limit tier',
      description: 'Business-initiated unique users per 24h. Identifiers, not numbers, so a Meta tier change is a data edit',
      icon: 'IconStairsUp',
      type: FieldType.SELECT,
      defaultValue: "'TIER_250'",
      options: [
        { value: 'TIER_250', label: '250 / 24h', position: 0, color: 'red' },
        { value: 'TIER_1K', label: '1 000 / 24h', position: 1, color: 'orange' },
        { value: 'TIER_2K', label: '2 000 / 24h', position: 2, color: 'amber' },
        { value: 'TIER_10K', label: '10 000 / 24h', position: 3, color: 'lime' },
        { value: 'TIER_100K', label: '100 000 / 24h', position: 4, color: 'green' },
        { value: 'TIER_UNLIMITED', label: 'Unlimited', position: 5, color: 'blue' },
      ],
    },
    {
      universalIdentifier: f('tierUniqueUsersUsed'),
      name: 'tierUniqueUsersUsed',
      label: 'Tier users used',
      description: 'Business-initiated unique users consumed in the rolling 24h (AR-21)',
      icon: 'IconUsers',
      type: FieldType.NUMBER,
      defaultValue: 0,
    },
    {
      universalIdentifier: f('tierWindowStartedAt'),
      name: 'tierWindowStartedAt',
      label: 'Tier window started at',
      icon: 'IconClockPlay',
      type: FieldType.DATE_TIME,
      isNullable: true,
    },
    {
      universalIdentifier: f('throughputPerSecond'),
      name: 'throughputPerSecond',
      label: 'Meta throughput / s',
      description: 'Meta-reported ceiling, informational',
      icon: 'IconGauge',
      type: FieldType.NUMBER,
      defaultValue: 80,
    },
    {
      universalIdentifier: f('sendThrottlePerSecond'),
      name: 'sendThrottlePerSecond',
      label: 'Send throttle / s',
      description: 'Our own ceiling, kept well below Meta’s (AR-12)',
      icon: 'IconBrakes',
      type: FieldType.NUMBER,
      defaultValue: 20,
    },
    {
      universalIdentifier: f('interactiveCursorAt'),
      name: 'interactiveCursorAt',
      label: 'Interactive pacing cursor',
      description: 'Next free send slot on the interactive lane (specs/00 D-5)',
      icon: 'IconCursorText',
      type: FieldType.DATE_TIME,
      isNullable: true,
    },
    {
      universalIdentifier: f('campaignCursorAt'),
      name: 'campaignCursorAt',
      label: 'Campaign pacing cursor',
      description: 'Next free send slot on the campaign lane (specs/00 D-5)',
      icon: 'IconCursorText',
      type: FieldType.DATE_TIME,
      isNullable: true,
    },
    {
      universalIdentifier: f('webhookLastEventAt'),
      name: 'webhookLastEventAt',
      label: 'Last webhook event',
      icon: 'IconWebhook',
      type: FieldType.DATE_TIME,
      isNullable: true,
    },
    {
      universalIdentifier: f('webhookLastVerifiedAt'),
      name: 'webhookLastVerifiedAt',
      label: 'Last webhook handshake',
      icon: 'IconCircleCheck',
      type: FieldType.DATE_TIME,
      isNullable: true,
    },
    {
      universalIdentifier: f('tokenLastCheckedAt'),
      name: 'tokenLastCheckedAt',
      label: 'Token last checked',
      icon: 'IconKey',
      type: FieldType.DATE_TIME,
      isNullable: true,
    },
    {
      universalIdentifier: f('defaultCountryCallingCode'),
      name: 'defaultCountryCallingCode',
      label: 'Default calling code',
      description: 'Applied when normalising nationally-formatted numbers (FR-CID-1)',
      icon: 'IconWorld',
      type: FieldType.TEXT,
      defaultValue: "'+244'",
    },
    {
      universalIdentifier: f('isTestAccount'),
      name: 'isTestAccount',
      label: 'Test account',
      description: 'Flags a Meta test number so every surface can badge it (FR-ACC-5)',
      icon: 'IconFlask',
      type: FieldType.BOOLEAN,
      defaultValue: false,
    },
    {
      universalIdentifier: f('contactAutoCreationEnabled'),
      name: 'contactAutoCreationEnabled',
      label: 'Auto-create contacts',
      description: 'Create a Person for unknown inbound numbers (FR-CID-3)',
      icon: 'IconUserPlus',
      type: FieldType.BOOLEAN,
      defaultValue: true,
    },
    {
      universalIdentifier: f('autoAssignStrategy'),
      name: 'autoAssignStrategy',
      label: 'Auto-assignment',
      icon: 'IconUsersGroup',
      type: FieldType.SELECT,
      defaultValue: "'NONE'",
      options: [
        { value: 'NONE', label: 'None', position: 0, color: 'gray' },
        { value: 'ROUND_ROBIN', label: 'Round robin', position: 1, color: 'blue' },
      ],
    },
    {
      universalIdentifier: f('assignmentMemberIds'),
      name: 'assignmentMemberIds',
      label: 'Assignment group',
      description:
        'Workspace member ids eligible for round-robin. An ARRAY rather than a relation to avoid a join object with no other purpose (specs/05 §3.3)',
      icon: 'IconUsers',
      type: FieldType.ARRAY,
      isNullable: true,
      universalSettings: { maxNumberOfValues: 60 },
    },
    {
      universalIdentifier: f('lastAssignedIndex'),
      name: 'lastAssignedIndex',
      label: 'Round-robin cursor',
      icon: 'IconRotate',
      type: FieldType.NUMBER,
      defaultValue: 0,
    },
    {
      universalIdentifier: f('visibilityMode'),
      name: 'visibilityMode',
      label: 'Thread visibility',
      description: 'Shared across the workspace, or restricted to assignee and admins (SEC-7)',
      icon: 'IconEye',
      type: FieldType.SELECT,
      defaultValue: "'SHARED'",
      options: [
        { value: 'SHARED', label: 'Shared', position: 0, color: 'green' },
        { value: 'RESTRICTED', label: 'Restricted', position: 1, color: 'orange' },
      ],
    },
  ],
});
