import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  ACCOUNT_STATUS,
  CAMPAIGN_STATUS,
  CONSENT_METHOD,
  CONSENT_STATUS,
  DIRECTION,
  EXCLUSION_REASON,
  MESSAGE_STATUS,
  MESSAGE_TYPE,
  MESSAGING_TIER,
  QUALITY,
  RECIPIENT_STATUS,
  TEMPLATE_CATEGORY,
  TEMPLATE_STATUS,
  THREAD_STATUS,
  WEBHOOK_PROCESSING_STATUS,
  WINDOW_KIND,
  WINDOW_STATE,
} from '../domain/constants';

/**
 * `src/domain/constants.ts` against the enums the *server* actually generated.
 *
 * Every handler compares against the constants; every write must satisfy the
 * schema. Nothing checks that the two agree — a SELECT option renamed in a
 * field definition, or a constant edited without a re-apply, typechecks
 * perfectly and fails at runtime on a real customer message.
 *
 * The generated client is regenerated by `yarn twenty dev:build` from the live
 * workspace, so this compares our source of truth against the server's.
 */

// The generated file is not an exported subpath, so it is read by path.
const SCHEMA = readFileSync(
  join(process.cwd(), 'node_modules/twenty-client-sdk/dist/core/generated/schema.ts'),
  'utf8',
);

const schemaEnum = (name: string): string[] => {
  const match = new RegExp(`export type ${name} = ([^\\n]+)`).exec(SCHEMA);

  if (match === null) throw new Error(`${name} is not in the generated schema`);

  return match[1]!
    .split('|')
    .map((member) => member.trim().replace(/^'|'$/g, ''))
    .sort();
};

const constantValues = (constants: Record<string, string>): string[] =>
  Object.values(constants).sort();

describe('domain constants match the generated schema', () => {
  it.each([
    ['WhatsappThreadStatusEnum', THREAD_STATUS],
    ['WhatsappThreadWindowStateEnum', WINDOW_STATE],
    ['WhatsappThreadWindowKindEnum', WINDOW_KIND],
    ['WhatsappMessageDirectionEnum', DIRECTION],
    ['WhatsappMessageMessageTypeEnum', MESSAGE_TYPE],
    ['WhatsappMessageStatusEnum', MESSAGE_STATUS],
    ['WhatsappMessageTemplateCategoryEnum', TEMPLATE_CATEGORY],
    ['WhatsappTemplateStatusEnum', TEMPLATE_STATUS],
    ['WhatsappTemplateQualityScoreEnum', QUALITY],
    ['WhatsappAccountStatusEnum', ACCOUNT_STATUS],
    ['WhatsappAccountQualityRatingEnum', QUALITY],
    ['WhatsappAccountMessagingLimitTierEnum', MESSAGING_TIER],
    ['WhatsappCampaignStatusEnum', CAMPAIGN_STATUS],
    ['WhatsappCampaignRecipientStatusEnum', RECIPIENT_STATUS],
    ['WhatsappCampaignRecipientExclusionReasonEnum', EXCLUSION_REASON],
    ['WhatsappConsentEventMethodEnum', CONSENT_METHOD],
    ['WhatsappConsentEventPreviousStatusEnum', CONSENT_STATUS],
    ['PersonWhatsappOptInStatusEnum', CONSENT_STATUS],
    ['WhatsappWebhookEventProcessingStatusEnum', WEBHOOK_PROCESSING_STATUS],
  ] as [string, Record<string, string>][])('%s', (name, constants) => {
    expect(schemaEnum(name)).toEqual(constantValues(constants));
  });

  /**
   * The one deliberate subset: a consent *event* records a change, and there is
   * no such thing as changing someone's status to `UNKNOWN` — that is the
   * absence of a decision, not a decision.
   */
  it('narrows the consent event target status to real decisions', () => {
    expect(schemaEnum('WhatsappConsentEventNewStatusEnum')).toEqual(['OPTED_IN', 'OPTED_OUT']);
  });

  it('read a schema that actually contains our objects', () => {
    expect(SCHEMA).toContain('WhatsappThreadGenqlSelection');
    expect(SCHEMA.length).toBeGreaterThan(100_000);
  });
});
